# ==========================
# CellViT Inference Config
# ==========================

# Model selection (REQUIRED)
model: SAM
nuclei_taxonomy: binary

inference:
  batch_size: 16

output_format:
  outdir: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database_2/DICOM/output
  geojson: True

process_wsi:
  wsi_path: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database_2/DICOM/File-2

system:
  cpu_count: 16
  ray_remote_cpus: 4

debug: True
