model: SAM

output_format:
  outdir: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database/XXL/output
  geojson: True

process_wsi:
  wsi_path: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database/XXL/input/TCGA-XS-A8TJ-01Z-00-DX1.3CB10EF8-8A92-472B-8B5D-6CA88C8A70D5.svs

system:
  cpu_count: 16
  ray_remote_cpus: 4

debug: True
