# ==========================
# CellViT Inference Config
# ==========================

# Model selection (REQUIRED)
model: HIPT

inference:


output_format:
  outdir: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database_2/BRACS/output
  geojson: True

process_wsi:
  wsi_path: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database_2/BRACS/input/BRACS_1640_N_3_cropped.tiff
  wsi_mpp: 0.25
  wsi_magnification: 40

system:
  cpu_count: 16

# system:
#   cpu_count:          # OPTIONAL | int: Number of CPU cores to use for inference.
#                       # Default: Uses system configuration.
#   ray_worker:         # OPTIONAL | int: Number of ray worker to use for inference. Limited by cpu_count.
#                       # Default: Uses system configuration.
#   ray_remote_cpus:    # OPTIONAL | int: Number of cpus per ray worker.
#                       # Default: Uses system configuration.

debug: True
