model: SAM

output_format:
  outdir: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database/Medium-Slide/output
  geojson: True

process_wsi:
  wsi_path: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database/Medium-Slide/input/ID_1002_LOC_3_TIME_2_BUJSK2080_STATUS_1_UID_8.svs

debug: True
