# ==========================
# CellViT Inference Config
# ==========================

# Model selection (REQUIRED)
model: SAM
nuclei_taxonomy: binary

inference:
  batch_size: 16

output_format:
  outdir: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database_2/DICOM/output
  geojson: True

process_dataset:
  wsi_folder: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database_2/DICOM/
  wsi_extension: dcm


system:
  cpu_count: 16
  ray_remote_cpus: 4

debug: True
