model: SAM

inference:
  batch_size: 16

output_format:
  outdir: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database/Large-Slide/output
  geojson: True

process_wsi:
  wsi_path: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database/Large-Slide/input/TCGA-R8-A6MO-01Z-00-DXA.CD6E7624-8EC3-4431-A3DC-2739419F9E12.svs

system:
  cpu_count: 16
  ray_remote_cpus: 4

debug: True
