# ==========================
# CellViT Inference Config
# ==========================

# Model selection (REQUIRED)
model: SAM
nuclei_taxonomy: binary

inference:
  batch_size: 16

output_format:
  outdir: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database_2/BRACS/output_binary_2
  geojson: True

process_dataset:
  wsi_folder: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database_2/BRACS/input/
  wsi_magnification: 40
  wsi_mpp: 0.25
  wsi_extension: tiff

system:
  cpu_count: 16
  ray_remote_cpus: 4

debug: True
