# ==========================
# CellViT Inference Config
# ==========================

# Model selection (REQUIRED)
model: SAM
nuclei_taxonomy: nucls_main


output_format:
  outdir: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database/Medium-Slide/output_nucls_main
  geojson: True

process_wsi:
  wsi_path: /home/jovyan/cellvit-small/CellViT-plus-plus/test_database/Medium-Slide/input/ID_1002_LOC_3_TIME_2_BUJSK2080_STATUS_1_UID_8.svs
  wsi_mpp: 0.25
  wsi_magnification: 40

system:
  cpu_count: 16
  ray_remote_cpus: 4

debug: True
