# ==========================
# CellViT Inference Config
# ==========================

# Model selection (REQUIRED)
model: HIPT

output_format:
  outdir: ./test_results/x40_svs/ray_worker_cpu/HIPT
  geojson: True

process_dataset:
  wsi_folder: ./test_database/x40_svs

system:
  cpu_count: 16
  ray_worker: 4

debug: True
